
spring:
  profiles:
    active: dev

---
server:
  port: 9527

spring:
  profiles: dev
  application:
    name: springcloud-zuul

# 向注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9527

# 配置 zuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /airnn

---
server:
  port: 9527

spring:
  profiles: test
  application:
    name: springcloud-zuul

# 向注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9527

# 配置 zuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /airnn

---
server:
  port: 9527

spring:
  profiles: prod
  application:
    name: springcloud-zuul

# 向注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9527

# 配置 zuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /airnn